### PR TITLE
Update to reason-react-native

### PR DESCRIPTION
**Pull request by DCKT**
Hello !

I've updated the template to support the latest version of `bs-react-native` which is `reason-react-native` [now](https://reasonml-community.github.io/reason-react-native/en/blog/2019-06-17-hello-reason-react-native/)

Every bindings must be updated, it's a lot of work sadly, I'll try to take some times to update the maximum I can.

What do you think ?

### CODE REVIEW

**Comment by FiberJW** [comment]
I looked into this, but using reason-react-native is an app-breaking experience when binding to components written as React Classes. JSX3 has little to no interop with class-bound components and therefore, all Expo components wouldn't work. Do you have a workaround that I'm not aware of? If so, let's implement that. If not, I believe that this library and template will have to continue to be under JSX2 for now.

**Comment by DCKT** [comment]
Yes it's breaking everything so it must be a major release.
There is no regression with reason-react-native, every bindings written now can be reused, [it's not mandatory to use [@react.component]](https://reasonml.github.io/reason-react/docs/en/components#hand-writing-components).

The painful things is this will works only if every components has been rewritten 😒

**Comment by dangdennis** [comment]
Every component being the bindings? Or the actual components within a jsx2 project? There's always the option of introducing `bs-react-native-jsx3-compat` into this library as a minor version bump.

Then making a major version bump when migrating from bs-react-native to reason-react-native.

**Comment by FiberJW** [comment]
The components written in JS that are written using Classes don't work when trying to use them in a ReasonReact JSX3 component. I did that "it's not mandatory to use [@react.component]" route, but they don't account for JS class components, they only account for migrating JS function components. AFAICT there's no migration strategy for migrating JS class bindings from Reason.reactClass to (props) => React.element types that JSX3 components need as children

**Comment by FiberJW** [comment]
I assume that's why you deleted Expo.LinearGradient from the template, am I right @DCKT ? I went throught the same process

**Comment by FiberJW** [comment]
and @dangdennis i mean every JS Class component wrapped to be a Reason component (the bindings)

**Comment by FiberJW** [comment]
I think i may have just screwed up trying to rewrite bindings, but I have yet to see a migration example in the wild for moving over JS class bindings

**Comment by FiberJW** [comment]
It looks like reason-react-native itself gets around this by adding this to every class component they're binding to Reason: https://github.com/reasonml-community/reason-react-native/blob/master/reason-react-native/src/elements/NativeElement.re

See https://github.com/reasonml-community/reason-react-native/blob/master/reason-react-native/src/components/Button.re vs. https://github.com/reasonml-community/reason-react-native/blob/master/bs-react-native/src/components/button.re

Just using the [@react.component] syntax has led to the types breaking or even the app breaking at runtime, but it looks like the type element stuff that has been done seems to work around that -- at least in RRN's case.

**Comment by dangdennis** [comment]
I have no idea what that NativeElements is doing. Can you explain?

**Comment by FiberJW** [comment]
I'm not the one who wrote it, but I assume it's faking the type signature of a React.element component so that the class imported JS class is usable as a child of a JSX3 component

**Comment by FiberJW** [comment]
@dangdennis @DCKT i made reason-expo an monorepo which makes it easier to contribute and test your changes. i'll look into trying to update to JSX3, but now it's easier for you to do so as well if you'd like.

**Comment by dangdennis** [comment]
This is great. Thanks Juwan, I'll look into testing around options as well.

**Comment by DCKT** [comment]
Hi @FiberJW ! 
Sorry for the delay, I've been quite busy lately. The monorepo idea is excellent, this will allow us to convert api progressively to JSX3. I'll try to take some times to convert some bindings

**Comment by FiberJW** [comment]
I figured it out. I was overcomplicating things trying to use `[@bs.as]` in LinearGradient to map end_ to "end" which is the name of a prop that's shadowed by a keyword in ReasonML. It isn't documented anywhere, but when you use an underscore at the beginning of a function parameter's name which is normally a keyword, it will compile away the underscore. There are no issues with integrating React classes to JSX3 function components, just this really obscure behavior. will start migrating a few components to jsx3 soon.

**Comment by dangdennis** [comment]
Congrats. Awesome progress, sir.

**Comment by FiberJW** [comment]
I've handled it now, but thanks for the contribution!

**Comment by DCKT** [comment]
Wow awesome thanks for your work !

**Pull request closed without merging**
